// Category constants to ensure consistency across the application
export const CATEGORY_CODES = {
  EVENT_PLANNERS: '01',
  VENUES: '02', 
  PHOTOGRAPHERS: '03',
  DECORATORS: '04',
  CATERERS: '05',
  MAKEUP_ARTISTS: '06',
  DJS_LIGHTING_ENTERTAINMENT: '07',
  ANCHORS: '08',
  TRANSPORTATION_SERVICES: '09',
  FASHION_COSTUME_DESIGNERS: '10',
  TENT_EQUIPMENT_RENTALS: '11'
} as const;

export const CATEGORY_NAMES = {
  [CATEGORY_CODES.EVENT_PLANNERS]: 'Event Planners',
  [CATEGORY_CODES.VENUES]: 'Venues',
  [CATEGORY_CODES.PHOTOGRAPHERS]: 'Photography/Videography',
  [CATEGORY_CODES.DECORATORS]: 'Decorators',
  [CATEGORY_CODES.CATERERS]: 'Caterers',
  [CATEGORY_CODES.MAKEUP_ARTISTS]: 'Makeup Artists',
  [CATEGORY_CODES.DJS_LIGHTING_ENTERTAINMENT]: 'DJs, Lighting, and Entertainment',
  [CATEGORY_CODES.ANCHORS]: 'Anchors',
  [CATEGORY_CODES.TRANSPORTATION_SERVICES]: 'Transportation Services',
  [CATEGORY_CODES.FASHION_COSTUME_DESIGNERS]: 'Fashion/Costume Designers',
  [CATEGORY_CODES.TENT_EQUIPMENT_RENTALS]: 'Tent & Equipment Rentals'
} as const;

// Reverse mapping for easy lookup
export const CATEGORY_NAME_TO_CODE: Record<string, string> = {
  'Event Planners': CATEGORY_CODES.EVENT_PLANNERS,
  'Venues': CATEGORY_CODES.VENUES,
  'Photography/Videography': CATEGORY_CODES.PHOTOGRAPHERS,
  'Decorators': CATEGORY_CODES.DECORATORS,
  'Caterers': CATEGORY_CODES.CATERERS,
  'Makeup Artists': CATEGORY_CODES.MAKEUP_ARTISTS,
  'DJs, Lighting, and Entertainment': CATEGORY_CODES.DJS_LIGHTING_ENTERTAINMENT,
  'Anchors': CATEGORY_CODES.ANCHORS,
  'Transportation Services': CATEGORY_CODES.TRANSPORTATION_SERVICES,
  'Fashion/Costume Designers': CATEGORY_CODES.FASHION_COSTUME_DESIGNERS,
  'Tent & Equipment Rentals': CATEGORY_CODES.TENT_EQUIPMENT_RENTALS
};

// Helper functions
export const getCategoryCode = (categoryName: string): string => {
  return CATEGORY_NAME_TO_CODE[categoryName] || '';
};

export const getCategoryName = (categoryCode: string): string => {
  return CATEGORY_NAMES[categoryCode as keyof typeof CATEGORY_NAMES] || '';
};

// Category list for dropdowns and selections
export const CATEGORY_LIST = [
  { code: CATEGORY_CODES.EVENT_PLANNERS, name: CATEGORY_NAMES[CATEGORY_CODES.EVENT_PLANNERS] },
  { code: CATEGORY_CODES.VENUES, name: CATEGORY_NAMES[CATEGORY_CODES.VENUES] },
  { code: CATEGORY_CODES.PHOTOGRAPHERS, name: CATEGORY_NAMES[CATEGORY_CODES.PHOTOGRAPHERS] },
  { code: CATEGORY_CODES.DECORATORS, name: CATEGORY_NAMES[CATEGORY_CODES.DECORATORS] },
  { code: CATEGORY_CODES.CATERERS, name: CATEGORY_NAMES[CATEGORY_CODES.CATERERS] },
  { code: CATEGORY_CODES.MAKEUP_ARTISTS, name: CATEGORY_NAMES[CATEGORY_CODES.MAKEUP_ARTISTS] },
  { code: CATEGORY_CODES.DJS_LIGHTING_ENTERTAINMENT, name: CATEGORY_NAMES[CATEGORY_CODES.DJS_LIGHTING_ENTERTAINMENT] },
  { code: CATEGORY_CODES.ANCHORS, name: CATEGORY_NAMES[CATEGORY_CODES.ANCHORS] },
  { code: CATEGORY_CODES.TRANSPORTATION_SERVICES, name: CATEGORY_NAMES[CATEGORY_CODES.TRANSPORTATION_SERVICES] },
  { code: CATEGORY_CODES.FASHION_COSTUME_DESIGNERS, name: CATEGORY_NAMES[CATEGORY_CODES.FASHION_COSTUME_DESIGNERS] },
  { code: CATEGORY_CODES.TENT_EQUIPMENT_RENTALS, name: CATEGORY_NAMES[CATEGORY_CODES.TENT_EQUIPMENT_RENTALS] }
];
